### ISSUE TITLE
README.md is a good start but can use more

### ISSUE THREAD

**Issue by dacb** [yhchen24/Missing-Density-PDB#1]
You've got a great start on your README.md, but it can use more work.  Remember that your README.md is the landing page of your repository. It should have complete documentation to your project or pointers to it, including how to install, prepare an environment for, and how to use your software. Also, badges from CI are good there too.

**Comment by jennybennett** [comment]
Thanks for the feedback! We've implemented badges, included install instructions, and additional information on how to use our software.
