### ISSUE TITLE
Repository structure

### ISSUE THREAD

**Issue by dacb** [yhchen24/Missing-Density-PDB#3]
I notice in the module directory, you don't have a `__init__.py` and there are jupyter notebooks.  If the notebooks are part of the demo, they probably belong in a different directory.  Also, you will need a `test` directory in the module directory with your unit tests.  The `.csv` files should probably go into a `data` directory in the module directory.

Make sure you follow the repository layout pattern in this PDF: https://github.com/UWDIRECT/UWDIRECT.github.io/raw/master/Wi20_content/SEDS/L9.Project_Structure.pdf

**Comment by jennybennett** [comment]
Thanks for the feedback! We have added __init__.py to all of our modules/submodules and included a tests folder.
